export const FETCH_EMPLOYEES = "FETCH_EMPLOYEEES";
export const FETCH_EMPLOYEES_INIT = "FETCH_EMPLOYEES_INIT";

export const FETCH_EMPLOYEES_SUCCESS = "FETCH_EMPLOYEES_SUCCESS";
export const FETCH_EMPLOYEES_ERROR = "FETCH_EMPLOYEES_ERROR";
export const UPDATE_EMPLOYEE_ASSIGMENT = "UPDATE_EMPLOYEE_ASSIGMENT";

export const SAVE_EMP_ASSIGNMT = "SAVE_EMP_ASSIGNMT";
