export const FETCH_WORK_ORDERS = "FETCH_WORK_ORDERS";
export const FETCH_WORK_ORDERS_INIT = "FETCH_WORK_ORDERS_INIT";
export const FETCH_WORK_ORDERS_SUCCESS = "FETCH_WORK_ORDERS_SUCCESS";
export const FETCH_WORK_ORDERS_ERROR = "FETCH_WORK_ORDERS_ERROR";
export const ASSIGN_TASK = "ASSIGN_TASK";
